name: build

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build.yml"
      - "**.zig"
      - "**.zon"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "**.zig"
      - "**.zon"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            target: x86_64-linux-musl
            zig-version: master
            install: sudo apt-get update && sudo apt-get install -y sqlite3
            shell: bash
          - os: macos-latest
            platform: macos
            target: aarch64-macos
            zig-version: master
            install: brew install sqlite
            shell: bash
          - os: windows-latest
            platform: windows
            target: x86_64-windows-gnu
            zig-version: master
            install: winget install --id SQLite.sqlite -e --accept-source-agreements --accept-package-agreements
            shell: pwsh

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Grab Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Install sqlite
        shell: ${{ matrix.shell }}
        run: ${{ matrix.install }}

      - name: Build ${{ matrix.platform }}
        shell: ${{ matrix.shell }}
        run: zig build -Dtarget=${{ matrix.target }}
